#!/usr/bin/env bash

sink_info=($(pactl info | grep Sink))
default_sink_name=${sink_info[2]}
info=$(pactl list sinks | grep -A 7 "Name: $default_sink_name")
mute_line=($(echo "$info" | grep Mute))
if [ "${mute_line[1]}" == "yes" ] 
then
    echo "MUTE"
else
    echo $(echo $info | grep -o '[[:digit:]]\{1,3\}%' | head -1) 
fi
