#!/usr/bin/env bash

sink_info=($(pactl info | grep Sink))
default_sink_name=${sink_info[2]}
info=$(pactl list sinks | grep -A 7 "Name: $default_sink_name")
echo $(echo $info | grep -o '[[:digit:]]\{1,3\}%' | head -1) 
